### ISSUE TITLE
Pterodactyl v1.11.2 Issues

### ISSUE THREAD

**Issue by Abadima** [Sigma-Production/PteroFreeStuffinstaller#57]
**Did you run on a clean panel?**
(Pterodactyl did a major refactor a while back)
Yes

**Describe the bug**
With the newer version of the panel, the themes don't appear fully working, screenshot shows below.

**To Reproduce**
1. Start Script
2. Select DarkNColor (I chose DarkNPurple)
3. Run a successful install
4. See panel

**Expected behavior**
The theme to be fully working, instead it did not apply to the background

**Screenshots**
![image](https://user-images.githubusercontent.com/39747270/211080630-5cbe27c3-16ad-4e20-8c5f-b8b2f24b4f2c.png)

**Comment by Abadima** [comment]
I should've mentioned it earlier, but the themes aren't applying to the main colours

**Comment by finnie2006** [comment]
Yes its a known issue that the background is not working

**Comment by Abadima** [comment]
Ah alright, any estimates as to when you can have it fixed?
